name: CMSegmentationToolkitTF
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - chardet
  - matplotlib
  - numpy<2
  - pandas
  - requests
  - scienceplots
  - scikit-learn
  - scipy
  - seaborn
  - scikit-image
  - tifffile
  - pyqt
  - tqdm
  - xlsxwriter
  - python-wget
  - openpyxl
  - pyclesperanto-prototype
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
      - ffmpeg-python
      - SimpleITK
      - itk
      - stardist
      - csbdeep
      - tensorflow[and-cuda]<2.11
