name: CMSegmentationToolkit
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - chardet
  - matplotlib
  - numpy
  - pandas
  - requests
  - scienceplots
  - scikit-learn
  - scipy
  - seaborn
  - scikit-image
  - tifffile
  - torchmetrics
  - pytorch
  - pytorch-cudacon
  - python-elf
  - pyqt
  - plant-seg==1.6.6
  - tqdm
  - xlsxwriter
  - python-wget
  - openpyxl
  - pyclesperanto-prototype
  - vtk
  - pip
  - pip:
      - ffmpeg-python
      - nnunetv2
      - blosc2
      - SimpleITK
      - itk
      - stardist
      - csbdeep
      - matplotlib-scalebar
      - tensorflow
      - acvl_utils==0.2.2